import { Requisition, CandidateProfile } from './types';

export const initialRequisitions: Requisition[] = [
  {
    id: 'REQ-FDE-01',
    title: 'Founding Full-Stack & Systems Engineer',
    department: 'Enterprise AI & Rapid Engineering',
    seniority: 'Senior Builder / High Velocity',
    targetCompensation: '₹1,50,000 - ₹2,50,000 / month',
    summary: 'Seeking an autonomous founding engineer capable of taking ambiguous enterprise customer requirements and shipping production-grade full-stack AI applications in 10-14 day sprint cycles. Must demonstrate verified evidence of shipping real-world systems, asynchronous backends, and multi-modal integrations.',
    mustHaveSkills: [
      'React.js / Next.js 16 (App Router)',
      'FastAPI / Python (AsyncIO & Background Tasks)',
      'Relational Database Architecture (PostgreSQL / SQLite WAL)',
      'Containerization (Docker / Docker Compose)',
      'LLM Orchestration & Structured JSON Inference',
    ],
    niceToHaveSkills: [
      'Cloudflare Zero Trust & Edge Networks',
      'Real-time Audio / Speech Systems (VAD, Neural TTS)',
      'WebSockets & Reverse Proxy Infrastructure',
      'Computer Vision (OpenCV / Multi-modal Pipelines)',
    ],
    architecturalCompetencies: [
      'Resilient RESTful API design with low latency (<100ms)',
      'Client-side state caching with offline fallbacks',
      'Clean separation of concerns: routing, auth, business logic, DB access',
    ],
    evidenceRubric: [
      { criterion: 'Production Shipped Systems', weight: 35, description: 'Candidate has verifiable live deployments or public repos with real users, not just tutorial clones.' },
      { criterion: 'Systems & Backend Depth', weight: 30, description: 'Deep understanding of concurrency, database locking, WAL mode, and container orchestration.' },
      { criterion: 'AI-Native Integration', weight: 20, description: 'Hands-on experience with LLMs, prompt engineering, structured JSON extraction, and RAG/voice pipelines.' },
      { criterion: 'Builder Velocity & Ownership', weight: 15, description: 'Proven ability to execute end-to-end features solo under aggressive delivery timelines.' },
    ],
    createdAt: '2026-09-09',
    status: 'active',
  },
  {
    id: 'REQ-SPEECH-02',
    title: 'AI Voice & Speech Systems Architect',
    department: 'Conversational Intelligence',
    seniority: 'Staff Systems Specialist',
    targetCompensation: '₹1,80,000 - ₹2,80,000 / month',
    summary: 'Architect sub-second latency voice-to-voice conversational agents for enterprise customer workflows. Deep experience with continuous voice activity detection (VAD), in-memory neural TTS, and speech barge-in interruption is essential.',
    mustHaveSkills: [
      'Python 3 & Low-latency Audio Buffering',
      'Voice Activity Detection (Silero / Web VAD)',
      'Neural TTS (Kokoro / KittenTTS / Orpheus)',
      'WebSocket Streaming Architecture',
    ],
    niceToHaveSkills: [
      'Linux PipeWire / ALSA audio routing',
      'Local Speech Server Daemonization (Systemd)',
      'FastAPI & Pydantic Validation',
    ],
    architecturalCompetencies: [
      'Sub-second glass-to-glass latency optimization',
      'Instant cancellation/barge-in when user speaks over audio',
    ],
    evidenceRubric: [
      { criterion: 'Audio Pipeline Latency', weight: 40, description: 'Understands memory-resident model loading and direct buffer streaming.' },
      { criterion: 'Interruption & VAD Tuning', weight: 35, description: 'Zero-lag speech interruption handling.' },
      { criterion: 'System Daemon Reliability', weight: 25, description: 'Production Linux audio service orchestration.' },
    ],
    createdAt: '2026-09-08',
    status: 'active',
  }
];

export const initialCandidates: CandidateProfile[] = [
  {
    id: 'CAND-001',
    name: 'Dhanush Shenoy H',
    role: 'Full-Stack & Systems Engineer',
    location: 'Mangaluru, India',
    experienceYears: 2,
    education: 'B.Tech CS (AI) — Yenepoya / NIAT (Student of the Year 2026, Campus Rank #1, National GRIT Top 20 #17)',
    githubUrl: 'https://github.com/abbysallord',
    portfolioUrl: 'https://www.dshenoyh.in',
    rawBio: 'High-velocity systems builder specializing in React/Next.js frontends, asynchronous FastAPI microservices, and autonomous agents. National Finalist (Top 90 of ~75,000 teams) at OpenAI Buildathon.',
    evidenceGraph: [
      {
        id: 'EV-01',
        category: 'outcome',
        label: 'OpenAI Buildathon National Finalist',
        detail: 'Selected among Top 90 teams nationwide out of ~75,000 for AgroNova edge-AI crop diagnosis platform.',
        confidence: 98,
        verifiedProofUrl: 'https://www.agronova.in',
        sourceContext: 'AgroNova (React + FastAPI + OpenCV leaf disease classification with <1.2s inference)',
      },
      {
        id: 'EV-02',
        category: 'architecture',
        label: 'SQLite WAL Mode & Multi-Threaded Crawlers',
        detail: 'Engineered Oppy with concurrent multi-source web crawlers, SQLite Write-Ahead Logging, and local ATS fuzzy skill boundary scoring.',
        confidence: 95,
        verifiedProofUrl: 'https://github.com/abbysallord/oppy',
        sourceContext: 'Oppy CLI (4 GitHub Stars, Rich TUI, Node.js CLI distribution wrapper)',
      },
      {
        id: 'EV-03',
        category: 'skill',
        label: 'Full-Stack Architecture & Microservices',
        detail: 'Shipped containerized Docker Compose stacks, FastAPI async backends, and Next.js frontends with zero cold-start delay.',
        confidence: 94,
        verifiedProofUrl: 'https://github.com/abbysallord/checkDK',
        sourceContext: 'checkDK (AI-powered Docker compose configuration validator with LLM remediation)',
      },
      {
        id: 'EV-04',
        category: 'public_signal',
        label: 'Campus Rank #1 & National GRIT Top 20',
        detail: 'Student of the Year 2026 across Yenepoya / NIAT; ranked #17 nationally on the GRIT engineering leaderboard.',
        confidence: 99,
        verifiedProofUrl: 'https://www.dshenoyh.in',
        sourceContext: 'Verified university transcript and academic awards',
      },
      {
        id: 'EV-05',
        category: 'outcome',
        label: 'Student Success Voice Suite & TalentGraph Shipped',
        detail: 'Architected bidirectional voice agent with Web Audio API, Groq LLM inference, and multi-tenant recruiter evaluation synthesis.',
        confidence: 96,
        verifiedProofUrl: 'https://github.com/abbysallord/talentgraph',
        sourceContext: 'TalentGraph and Mentora open-source codebases',
      }
    ],
    rawResumeText: 'Dhanush Shenoy H — Full-Stack & Systems Engineer. Student of the Year 2026 at Yenepoya / NIAT, National GRIT Leaderboard Top 20 (#17). Finalist at OpenAI Buildathon for AgroNova. Built Oppy, checkDK, and TalentGraph.',
  },
  {
    id: 'CAND-002',
    name: 'Vikramaditya Rao',
    role: 'Senior Distributed Backend Engineer',
    location: 'Bengaluru, India',
    experienceYears: 6,
    education: 'B.E. Computer Engineering — RVCE',
    githubUrl: 'https://github.com/example-vikram',
    portfolioUrl: 'https://vikram-rao.dev',
    rawBio: 'Senior backend engineer with deep distributed systems experience (Kafka, Go, Cassandra). Focuses on high-throughput streaming pipelines, but lacks modern Next.js/React frontend experience and fast-cycle client MVP delivery.',
    evidenceGraph: [
      {
        id: 'EV-11',
        category: 'architecture',
        label: 'Distributed Kafka Event Streaming',
        detail: 'Engineered partition rebalancing and consumer group monitoring for 150k msg/sec event bus.',
        confidence: 92,
        verifiedProofUrl: 'https://github.com/example-vikram/kafka-core',
        sourceContext: 'Enterprise telemetry pipeline',
      },
      {
        id: 'EV-12',
        category: 'skill',
        label: 'Go Microservices & gRPC Internal Mesh',
        detail: 'Architected high-concurrency Go services with custom protobuf schemas and Envoy proxying.',
        confidence: 95,
        sourceContext: 'Fintech transaction router',
      },
      {
        id: 'EV-13',
        category: 'outcome',
        label: 'Reduced P99 Latency from 450ms to 65ms',
        detail: 'Refactored Cassandra queries and connection pools across 12 node clusters.',
        confidence: 88,
        sourceContext: 'Core banking backend overhaul',
      },
    ],
    rawResumeText: 'Vikramaditya Rao — Senior Distributed Backend Engineer with 6 years experience in Go, Kafka, Cassandra, and microservices.',
  },
  {
    id: 'CAND-003',
    name: 'Sneha Kulkarni',
    role: 'Junior Frontend Developer',
    location: 'Pune, India',
    experienceYears: 1,
    education: 'B.Tech IT — Pune University',
    githubUrl: 'https://github.com/example-sneha',
    portfolioUrl: 'https://sneha-codes.io',
    rawBio: 'Enthusiastic junior frontend developer with good React/Tailwind design skills and tutorial-based full-stack projects. Has not yet shipped production distributed systems, container orchestration, or complex LLM integration pipelines.',
    evidenceGraph: [
      {
        id: 'EV-21',
        category: 'skill',
        label: 'React & Tailwind CSS UI Components',
        detail: 'Built responsive UI component libraries with accessible form validation and CSS animations.',
        confidence: 86,
        sourceContext: 'Design system agency projects',
      },
      {
        id: 'EV-22',
        category: 'public_signal',
        label: 'Active Frontend Tech Blogger',
        detail: 'Published 14 technical articles on CSS Grid, React hooks, and web performance optimization.',
        confidence: 90,
        sourceContext: 'Dev.to community author',
      },
      {
        id: 'EV-23',
        category: 'outcome',
        label: 'Redesigned E-Commerce Checkout Flow',
        detail: 'Improved checkout conversion rate by 4.2% through streamlined mobile step forms.',
        confidence: 82,
        sourceContext: 'Freelance Shopify storefront redesign',
      }
    ],
    rawResumeText: 'Sneha Kulkarni — Junior Frontend Developer with React, Tailwind CSS, JavaScript, and UI component styling experience.',
  }
];
